// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1 AND organization_id = $2
`

type DeleteApplicationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.OrganizationID)
	return err
}

const findApplicationByID = `-- name: FindApplicationByID :one
SELECT id, name, slug, created_at, updated_at, organization_id
FROM applications
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type FindApplicationByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) FindApplicationByID(ctx context.Context, arg FindApplicationByIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, findApplicationByID, arg.ID, arg.OrganizationID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const findApplicationBySlug = `-- name: FindApplicationBySlug :one
SELECT id, name, slug, created_at, updated_at, organization_id
FROM applications
WHERE slug = $1 AND organization_id = $2
LIMIT 1
`

type FindApplicationBySlugParams struct {
	Slug           string
	OrganizationID uuid.UUID
}

func (q *Queries) FindApplicationBySlug(ctx context.Context, arg FindApplicationBySlugParams) (Application, error) {
	row := q.db.QueryRow(ctx, findApplicationBySlug, arg.Slug, arg.OrganizationID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :exec
INSERT INTO applications (id, name, slug, organization_id)
VALUES ($1, $2, $3, $4)
`

type InsertApplicationParams struct {
	ID             uuid.UUID
	Name           string
	Slug           string
	OrganizationID uuid.UUID
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) error {
	_, err := q.db.Exec(ctx, insertApplication,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OrganizationID,
	)
	return err
}
