// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints
WHERE id = $1 AND organization_id = $2
`

type DeleteEndpointParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.OrganizationID)
	return err
}

const deleteEndpointSubscription = `-- name: DeleteEndpointSubscription :exec
DELETE FROM endpoint_subscriptions
WHERE endpoint_id = $1 AND event_type_id = $2 AND organization_id = $3
`

type DeleteEndpointSubscriptionParams struct {
	EndpointID     uuid.UUID
	EventTypeID    uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteEndpointSubscription(ctx context.Context, arg DeleteEndpointSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteEndpointSubscription, arg.EndpointID, arg.EventTypeID, arg.OrganizationID)
	return err
}

const findEndpointByID = `-- name: FindEndpointByID :one
SELECT id, application_id, url, description, signing_secret, disabled, created_at, updated_at, organization_id
FROM endpoints
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type FindEndpointByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) FindEndpointByID(ctx context.Context, arg FindEndpointByIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, findEndpointByID, arg.ID, arg.OrganizationID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.Description,
		&i.SigningSecret,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const findEndpointByURL = `-- name: FindEndpointByURL :one
SELECT id, application_id, url, description, signing_secret, disabled, created_at, updated_at, organization_id
FROM endpoints
WHERE url = $1 AND organization_id = $2
LIMIT 1
`

type FindEndpointByURLParams struct {
	Url            string
	OrganizationID uuid.UUID
}

func (q *Queries) FindEndpointByURL(ctx context.Context, arg FindEndpointByURLParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, findEndpointByURL, arg.Url, arg.OrganizationID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Url,
		&i.Description,
		&i.SigningSecret,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const findSubscribedEventTypes = `-- name: FindSubscribedEventTypes :many
SELECT event_type_id
FROM endpoint_subscriptions
WHERE endpoint_id = $1 AND organization_id = $2
`

type FindSubscribedEventTypesParams struct {
	EndpointID     uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) FindSubscribedEventTypes(ctx context.Context, arg FindSubscribedEventTypesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findSubscribedEventTypes, arg.EndpointID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var event_type_id uuid.UUID
		if err := rows.Scan(&event_type_id); err != nil {
			return nil, err
		}
		items = append(items, event_type_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEndpoint = `-- name: InsertEndpoint :exec
INSERT INTO endpoints (id, application_id, organization_id, url, description, signing_secret)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEndpointParams struct {
	ID             uuid.UUID
	ApplicationID  uuid.UUID
	OrganizationID uuid.UUID
	Url            string
	Description    string
	SigningSecret  string
}

func (q *Queries) InsertEndpoint(ctx context.Context, arg InsertEndpointParams) error {
	_, err := q.db.Exec(ctx, insertEndpoint,
		arg.ID,
		arg.ApplicationID,
		arg.OrganizationID,
		arg.Url,
		arg.Description,
		arg.SigningSecret,
	)
	return err
}

const insertEndpointSubscription = `-- name: InsertEndpointSubscription :exec
INSERT INTO endpoint_subscriptions (endpoint_id, event_type_id, organization_id)
VALUES ($1, $2, $3)
`

type InsertEndpointSubscriptionParams struct {
	EndpointID     uuid.UUID
	EventTypeID    uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) InsertEndpointSubscription(ctx context.Context, arg InsertEndpointSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertEndpointSubscription, arg.EndpointID, arg.EventTypeID, arg.OrganizationID)
	return err
}
