// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_types.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEventType = `-- name: DeleteEventType :exec
DELETE FROM event_types
WHERE id = $1 AND organization_id = $2
`

type DeleteEventTypeParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteEventType(ctx context.Context, arg DeleteEventTypeParams) error {
	_, err := q.db.Exec(ctx, deleteEventType, arg.ID, arg.OrganizationID)
	return err
}

const findEventTypeByID = `-- name: FindEventTypeByID :one
SELECT id, application_id, name, payload_schema, created_at, updated_at, organization_id
FROM event_types
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type FindEventTypeByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) FindEventTypeByID(ctx context.Context, arg FindEventTypeByIDParams) (EventType, error) {
	row := q.db.QueryRow(ctx, findEventTypeByID, arg.ID, arg.OrganizationID)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.PayloadSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const findEventTypeByName = `-- name: FindEventTypeByName :one
SELECT id, application_id, name, payload_schema, created_at, updated_at, organization_id
FROM event_types
WHERE name = $1 AND application_id = $2 AND organization_id = $3
LIMIT 1
`

type FindEventTypeByNameParams struct {
	Name           string
	ApplicationID  uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) FindEventTypeByName(ctx context.Context, arg FindEventTypeByNameParams) (EventType, error) {
	row := q.db.QueryRow(ctx, findEventTypeByName, arg.Name, arg.ApplicationID, arg.OrganizationID)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.PayloadSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const insertEventType = `-- name: InsertEventType :exec
INSERT INTO event_types (id, name, application_id, organization_id, payload_schema)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventTypeParams struct {
	ID             uuid.UUID
	Name           string
	ApplicationID  uuid.UUID
	OrganizationID uuid.UUID
	PayloadSchema  []byte
}

func (q *Queries) InsertEventType(ctx context.Context, arg InsertEventTypeParams) error {
	_, err := q.db.Exec(ctx, insertEventType,
		arg.ID,
		arg.Name,
		arg.ApplicationID,
		arg.OrganizationID,
		arg.PayloadSchema,
	)
	return err
}
