// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMessageBatch = `-- name: ClaimMessageBatch :many
UPDATE messages
SET attempts = attempts + 1
WHERE id IN (
    SELECT id FROM messages
    WHERE status = 'pending' AND next_attempt_at <= now()
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, organization_id, application_id, event_type_id, payload, status, attempts
`

type ClaimMessageBatchRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ApplicationID  uuid.UUID
	EventTypeID    uuid.UUID
	Payload        []byte
	Status         string
	Attempts       int32
}

func (q *Queries) ClaimMessageBatch(ctx context.Context, batchSize int32) ([]ClaimMessageBatchRow, error) {
	rows, err := q.db.Query(ctx, claimMessageBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimMessageBatchRow
	for rows.Next() {
		var i ClaimMessageBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ApplicationID,
			&i.EventTypeID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, organization_id, application_id, event_type_id, payload, status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMessageParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ApplicationID  uuid.UUID
	EventTypeID    uuid.UUID
	Payload        []byte
	Status         string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.OrganizationID,
		arg.ApplicationID,
		arg.EventTypeID,
		arg.Payload,
		arg.Status,
	)
	return err
}

const markMessageFailed = `-- name: MarkMessageFailed :exec
UPDATE messages
SET status = 'failed'
WHERE id = $1
`

func (q *Queries) MarkMessageFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageFailed, id)
	return err
}

const markMessagePublished = `-- name: MarkMessagePublished :exec
UPDATE messages
SET status = 'published', published_at = now()
WHERE id = $1
`

func (q *Queries) MarkMessagePublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessagePublished, id)
	return err
}

const rescheduleMessage = `-- name: RescheduleMessage :exec
UPDATE messages
SET next_attempt_at = $1
WHERE id = $2
`

type RescheduleMessageParams struct {
	NextAttemptAt time.Time
	ID            uuid.UUID
}

func (q *Queries) RescheduleMessage(ctx context.Context, arg RescheduleMessageParams) error {
	_, err := q.db.Exec(ctx, rescheduleMessage, arg.NextAttemptAt, arg.ID)
	return err
}
