// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID             uuid.UUID
	Name           string
	Slug           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}

type Endpoint struct {
	ID             uuid.UUID
	ApplicationID  uuid.UUID
	Url            string
	Description    string
	SigningSecret  string
	Disabled       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}

type EndpointSubscription struct {
	EndpointID     uuid.UUID
	EventTypeID    uuid.UUID
	CreatedAt      time.Time
	OrganizationID uuid.UUID
}

type EventType struct {
	ID             uuid.UUID
	ApplicationID  uuid.UUID
	Name           string
	PayloadSchema  []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}

type Message struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ApplicationID  uuid.UUID
	EventTypeID    uuid.UUID
	Payload        []byte
	Status         string
	Attempts       int32
	NextAttemptAt  time.Time
	CreatedAt      time.Time
	PublishedAt    pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	Name           string
	LastName       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
}
